In [8]:
import os
os.environ["no_proxy"] = "localhost,127.0.0.1,.ebay.com,.vip,.ebayc3.com"
os.environ["https_proxy"] = "http://httpproxy-tcop.vip.ebay.com:80"

In [30]:
! pip install  openpyxl

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.python.org/simple
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
WARNING: Error parsing dependencies of pytorch-lightning: .* suffix can only be used with `==` or `!=` operators
    torch (>=1.8.*)
           ~~~~~~^
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: pip install --upgrade pip

In [ ]:
! pip install formulas

### Set up

In [3]:
import sys
import os

tmp = !hostname
if tmp[0].startswith('krylov'):
    on_kry = True
else: 
    on_kry = False
    
base_path = '/data/ebay/notebooks/olivyatan/Gen_signals'

print(base_path)

# sys.path.append(os.path.join(base_path, 'signals/'))
# sys.path.append(os.path.join(base_path, 'signals/src'))
sys.path.append(os.path.join(base_path, 'generative_signals/'))
sys.path.append(os.path.join(base_path, 'generative_signals/src'))
# sys.path.append(os.path.join(base_path, 'signals/workflows/pipelines/'))
# sys.path.append(os.path.join(base_path, 'signals/workflows/global_utils/'))
# sys.path.append(os.path.join(base_path, 'signals/workflows'))
# sys.path.append(os.path.join(base_path, 'matans_sandbox/utils'))

os.chdir(os.path.join(base_path,'generative_signals'))
print(f"curr dir: {os.getcwd()}")

/data/ebay/notebooks/olivyatan/Gen_signals
curr dir: /data/ebay/notebooks/olivyatan/Gen_signals/generative_signals

In [4]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import os

import sys
import base64
from bs4 import BeautifulSoup
import re
import json
import os
from datetime import datetime
from functools import reduce
from typing import List
import gzip
import numpy as np

In [5]:
import importlib
def refresh_module(module_name):
    try:
        module = importlib.import_module(module_name)
        importlib.reload(module)
        module = importlib.import_module(module_name)
        globals().update(module.__dict__)
    except ImportError as e:
        print(f"Error importing module {module_name}: {e}")
        return None

In [6]:
import dev.data_extraction.extraction_funcs
importlib.reload(dev.data_extraction.extraction_funcs)
import dev.data_extraction.extraction_funcs
from dev.data_extraction.extraction_funcs import *

In [7]:
refresh_module('dev.generation.sigs_gen')
refresh_module('dev.generation.generators.base_sigs_generator')
refresh_module('dev.generation.generators.gpt_generator')

### Read data

In [6]:
file_path = "/data/ebay/notebooks/olivyatan/Gen_signals/generative_signals/notebooks/generation/HG_Matan_sample_50_examples.csv"

#### Read disagree

In [7]:
import pandas as pd
df_tagged = pd.read_csv(file_path, encoding='utf-8')

In [ ]:
final_label_disagree_df_#2_020225_pairs_hg.csv

In [9]:
#file_path = "/data/ebay/notebooks/olivyatan/Gen_signals/final_label_disagree_df_#2_020225_pairs_hg.csv"

In [9]:
file_path = "/data/ebay/notebooks/olivyatan/Gen_signals/Fashion_disagree_df_#2_020225_pairs_Highlighted.csv"

In [10]:
df_final_disagree = pd.read_csv(file_path, encoding='utf-8')

In [11]:
df_final_disagree.head(5)

,item_id,gen_sig_gpt,Final Label,comment,annotator_name,label,reason,comment.1,annotator_name_2,label_2,reason_2,comment_2,title,aspects,desc,match_type,match_column,disagreement_type,annotator_pair
0,2.262610e+11,100% Cotton Material,1.0,NaN,Yonatan,2.0,NaN,NaN,Guy,1,NaN,NaN,kinetic geometrics Cotton fabric henry glass ...,"{'brand': 'henry glass & co.', 'color': 'purpl...",Kinetic Geometric Henry Glass Fabrics 45 Inche...,exact,desc,"(1, 2.0)","('Guy', 'Yonatan')"
1,2.630560e+11,Uv Ink Printed Directly,1.0,NaN,Yonatan,2.0,NaN,NaN,Guy,1,NaN,NaN,*aluminum* danger beware of the derrick hand 8...,"{'color': 'white', 'core_product_type': 'wall ...","8"" x 12"" Metal Novelty Sign This item is for o...",exact,desc,"(1, 2.0)","('Guy', 'Yonatan')"
2,1.158700e+11,Ribbon By The Yard,1.0,NaN,Yonatan,1.0,NaN,NaN,Guy,0,NaN,NaN,"3/8, 5/8, 7/8 & 1.5"" (1 yd) pumkin grosgrain R...","{'brand': 'plaid', 'color': 'multicolor', 'cor...",Cute Halloween pumpkins trim Ribbon. Cut in co...,exact,desc,"(0, 1.0)","('Guy', 'Yonatan')"
3,3.146120e+11,High Precision Counting,2.0,NaN,Yonatan,2.0,NaN,NaN,Guy,1,NaN,NaN,photoelectric automatic seed counter machine f...,{'brand': 'unbranded'},Automatic seeds counter for various shapes see...,exact,desc,"(1, 2.0)","('Guy', 'Yonatan')"
4,2.563890e+11,Genuine Oem Husqvarna Product,1.0,NaN,Yonatan,0.0,Very similar to title,NaN,Guy,1,NaN,NaN,Genuine Husqvarna 582625802 fuel tank unit ass...,"{'brand': 'Husqvarna', 'core_Product_type': 'g...","Genuine Oem Husqvarna Product, In STOCK! Husqv...",ngram+non ngram,desc,"(0.0, 1)","('Guy', 'Yonatan')"

In [11]:
df_final_disagree.head(5)

,item_id,gen_sig_gpt,final_label,final_reason,final_comment,ask:,annotator_name,label,reason,comment,annotator_name_2,label_2,reason_2,comment_2,title,aspects,desc,match_type,match_column,annotator_pair
0,256802207440,Long Sleeves,0,obvious from the image,Should be obvious from the image,NaN,Ortal,1.0,NaN,NaN,Matan,0.0,NaN,Seems not informative. Probably discernable fr...,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc,"('Matan', 'Ortal')"
1,256802207440,Durability,0,Not clear- incorrect grammer,NaN,NaN,Ortal,0.0,Not Clear,NaN,Matan,1.0,NaN,NaN,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc,"('Matan', 'Ortal')"
2,256802207440,Effortless Sophistication,2,NaN,NaN,NaN,Ortal,1.0,NaN,NaN,Matan,2.0,NaN,NaN,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc,"('Matan', 'Ortal')"
3,276836415475,Not Enhanced,1,NaN,NaN,NaN,Ortal,0.0,NaN,NaN,Matan,1.0,NaN,NaN,11.90cts.100%natural pink scolecite pear pair ...,"{'absorbency': None, 'accents': None, 'accesso...",GEMSTONEDESIRE Handling Time 4 Business Days P...,exact,aspects,"('Matan', 'Ortal')"
4,235902590697,Gusset 18,0,Too technical,NaN,NaN,Ortal,1.0,NaN,NaN,Matan,0.0,Off-Topic,18 is just the size of the Gusset,other brands trenta sei tote bag marche bag wi...,"{'absorbency': None, 'accents': None, 'accesso...",Description Condition: USED Actual size（cm） Gu...,exact,desc,"('Matan', 'Ortal')"

In [8]:
df_tagged.head(3)

,item_id,gen_sig_gpt,annotator_name,label,reason,comment,label2,reason2,comment2,annotator_name2,title,aspects,desc,match_type,match_column,Comments
0,226211925455,High Quality Materials,Matan,1.0,NaN,"In the listing itselt, under 'item_specifics' ...",NaN,NaN,NaN,Guy,pressure drain jetter hose nozzle flusher pipe...,"{'brand': 'unbranded', 'material': 'stainless ...",Product Description Features： * You will recei...,exact,desc,"In the listing itselt, under 'item_specifics' ..."
1,334848019142,Quality Hyway Brand,Matan,0.0,Trivial information,"The brand it indicated in the title, so it's o...",NaN,NaN,NaN,Guy,Hyway gasket set for sthl ms201t oem# 1145-007...,"{'Brand': 'Hyway', 'core_product_type': 'garde...",Hyway Gasket Set for STHL MS201T OEM# 1145-007...,exact,desc,NaN
2,315697921850,Unique Football Shape,Matan,0.0,Trivial information,It should be obvious from the title and image ...,NaN,NaN,NaN,Guy,sports curtain tiebacks Football curtain holdb...,"{'color': 'white', 'core_product_type': 'windo...",Related Hot Sale Patchwork Table Mat Ironing M...,exact,desc,NaN

In [ ]:
#!rm -rf /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_HG_pairs/*

In [1]:
!ls /data/ebay/data/olivyatan/Datasets/annotation_files/

tagging_2_020225_HG_pairs

#### Fashion xlsx files for annotation

In [12]:
!ls /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs/tagged_data

'highlighted_text_filtered_by_heuristic_sample-Fashion_Dimitri.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Gilad.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Guy.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Matan.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Ortal.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Tal.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Yonatan.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Yotam.xlsx - Highlighted.csv'

In [13]:
!mkdir /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs/tagged_data

mkdir: cannot create directory ‘/data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs/tagged_data’: File exists

In [14]:
!ls /data/ebay/notebooks/olivyatan/Gen_signals/

Fashion_disagree_df_#2_020225_pairs_Highlighted.csv
Untitled.ipynb
annotation_files_2_020225_hg_pairs
bad_cases_df_Fashion1_25unique_per_pair.xlsx
bad_cases_df_Fashion1_25unique_per_pair_forbidden_words.xlsx
bxkrylov-1.7.2-py3-none-any.whl
data
fashion_disagree_df_#2_020225_pairs.xlsx
generative_signals
generative_signals_gemini
generative_signals_old
generative_signals_old_1
generative_signals_science
highlighted_text_disagree_df_#2_020225_pairs_hg.xlsx
highlighted_text_filtered_by_heuristic_sample_Fashion1_25unique.xlsx
sig_data_extraction.ipynb

In [17]:
!mv /data/ebay/notebooks/olivyatan/Gen_signals/highlighted_text_filtered_by_heuristic_sample-Fashion_Dimitri.xlsx\ -\ Highlighted.csv \
/data/ebay/notebooks/olivyatan/Gen_signals/highlighted_text_filtered_by_heuristic_sample-Fashion_Gilad.xlsx\ -\ Highlighted.csv \
/data/ebay/notebooks/olivyatan/Gen_signals/highlighted_text_filtered_by_heuristic_sample-Fashion_Guy.xlsx\ -\ Highlighted.csv \
/data/ebay/notebooks/olivyatan/Gen_signals/highlighted_text_filtered_by_heuristic_sample-Fashion_Matan.xlsx\ -\ Highlighted.csv \
/data/ebay/notebooks/olivyatan/Gen_signals/highlighted_text_filtered_by_heuristic_sample-Fashion_Ortal.xlsx\ -\ Highlighted.csv \
/data/ebay/notebooks/olivyatan/Gen_signals/highlighted_text_filtered_by_heuristic_sample-Fashion_Tal.xlsx\ -\ Highlighted.csv \
/data/ebay/notebooks/olivyatan/Gen_signals/highlighted_text_filtered_by_heuristic_sample-Fashion_Yonatan.xlsx\ -\ Highlighted.csv \
/data/ebay/notebooks/olivyatan/Gen_signals/highlighted_text_filtered_by_heuristic_sample-Fashion_Yotam.xlsx\ -\ Highlighted.csv \
/data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs/tagged_data/

In [18]:
!ls /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs/tagged_data/

'highlighted_text_filtered_by_heuristic_sample-Fashion_Dimitri.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Gilad.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Guy.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Matan.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Ortal.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Tal.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Yonatan.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Yotam.xlsx - Highlighted.csv'

In [2]:
#mkdir /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs

In [5]:
mv /data/ebay/notebooks/olivyatan/Gen_signals/{highlighted_text_filtered_by_heuristic_sample-Fashion_Dimitri.xlsx,highlighted_text_filtered_by_heuristic_sample-Fashion_Gilad.xlsx,highlighted_text_filtered_by_heuristic_sample-Fashion_Guy.xlsx,highlighted_text_filtered_by_heuristic_sample-Fashion_Matan.xlsx,highlighted_text_filtered_by_heuristic_sample-Fashion_Ortal.xlsx,highlighted_text_filtered_by_heuristic_sample-Fashion_Tal.xlsx,highlighted_text_filtered_by_heuristic_sample-Fashion_Yonatan.xlsx,highlighted_text_filtered_by_heuristic_sample-Fashion_Yotam.xlsx} /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs/

In [13]:
mv /data/ebay/notebooks/olivyatan/Gen_signals/final_label_disagree_df_#2_020225_pairs_hg.csv /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_HG_pairs/

In [97]:
!rm -f /data/ebay/data/olivyatan/Datasets/annotation_files/aggregated_disagreement_annotations.xlsx

In [ ]:
!rm -f aggregated_disagreement_annotations.xlsx

In [20]:
!ls /data/ebay/data/olivyatan/Datasets/sample_tagging_hg

filtered_7k_df.parquet
gen_hg_2000_improved_promt.parquet
matan_regen.parquet
re_gen_title_exact.parquet
sampled_filtered_df.parquet
sampled_filtered_df_small.parquet
sampled_filtered_df_small_improved_prompt.parquet
sampled_filtered_df_small_improved_prompt_samePairs.parquet

In [14]:
!ls /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_HG_pairs

 final_label_disagree_df_#2_020225_pairs_hg.csv
 highlighted_text_disagree_df_#2_020225_pairs_hg.xlsx
'highlighted_text_filtered_by_heuristic_sample-HG_Guy.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-HG_Matan.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-HG_Ortal.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-HG_Tal.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-HG_Yonatan.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-HG_Yotam.xlsx - Highlighted.csv'

In [8]:
cd /data/ebay/data/olivyatan/Datasets/

/data/ebay/data/olivyatan/Datasets

In [9]:
mkdir /data/ebay/data/olivyatan/Datasets/annotation_files

In [12]:
mkdir /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_HG_pairs

In [99]:
!ls /data/ebay/data/olivyatan/Datasets/annotation_files

tagging_2_020225_HG_pairs

In [51]:
!ls /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_HG_pairs

 final_label_disagree_df_#2_020225_pairs_hg.csv
 highlighted_text_disagree_df_#2_020225_pairs_hg.xlsx
'highlighted_text_filtered_by_heuristic_sample-HG_Guy.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-HG_Matan.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-HG_Ortal.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-HG_Tal.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-HG_Yonatan.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-HG_Yotam.xlsx - Highlighted.csv'

In [89]:
!ls /data/ebay/notebooks/olivyatan/Gen_signals/

Untitled.ipynb			    generative_signals_old
annotation_files_2_020225_hg_pairs  generative_signals_old_1
bxkrylov-1.7.2-py3-none-any.whl     generative_signals_science
data				    sig_data_extraction.ipynb
generative_signals

In [15]:
#cp /data/ebay/notebooks/olivyatan/Gen_signals/{highlighted_text_filtered_by_heuristic_sample-HG_Guy.xlsx,highlighted_text_filtered_by_heuristic_sample-HG_Matan.xlsx,highlighted_text_filtered_by_heuristic_sample-HG_Ortal.xlsx,highlighted_text_filtered_by_heuristic_sample-HG_Tal.xlsx,highlighted_text_filtered_by_heuristic_sample-HG_Yonatan.xlsx,highlighted_text_filtered_by_heuristic_sample-HG_Yotam.xlsx,highlighted_text_filtered_by_heuristic_sample_small_300-HG.xlsx} /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_HG_pairs/

In [18]:
#mv /data/ebay/notebooks/olivyatan/Gen_signals/{highlighted_text_filtered_by_heuristic_sample-HG_Guy.xlsx,highlighted_text_filtered_by_heuristic_sample-HG_Matan.xlsx,highlighted_text_filtered_by_heuristic_sample-HG_Ortal.xlsx,highlighted_text_filtered_by_heuristic_sample-HG_Tal.xlsx,highlighted_text_filtered_by_heuristic_sample-HG_Yonatan.xlsx,highlighted_text_filtered_by_heuristic_sample-HG_Yotam.xlsx,highlighted_text_filtered_by_heuristic_sample_small_300-HG.xlsx} /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_HG_pairs/

In [ ]:
!mv /data/ebay/notebooks/olivyatan/Gen_signals/'highlighted_text_filtered_by_heuristic_sample-HG_Guy.xlsx - Highlighted.csv' \
     /data/ebay/notebooks/olivyatan/Gen_signals/'highlighted_text_filtered_by_heuristic_sample-HG_Matan.xlsx - Highlighted.csv' \
     /data/ebay/notebooks/olivyatan/Gen_signals/'highlighted_text_filtered_by_heuristic_sample-HG_Ortal.xlsx - Highlighted.csv' \
     /data/ebay/notebooks/olivyatan/Gen_signals/'highlighted_text_filtered_by_heuristic_sample-HG_Tal.xlsx - Highlighted.csv' \
     /data/ebay/notebooks/olivyatan/Gen_signals/'highlighted_text_filtered_by_heuristic_sample-HG_Yonatan.xlsx - Highlighted.csv' \
     /data/ebay/notebooks/olivyatan/Gen_signals/'highlighted_text_filtered_by_heuristic_sample-HG_Yotam.xlsx - Highlighted.csv' \
     /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_HG_pairs/

In [7]:
!mv /data/ebay/notebooks/olivyatan/Gen_signals/Sample_2_Fashion_Matan.xlsx\ -\ Highlighted.csv \
    /data/ebay/notebooks/olivyatan/Gen_signals/Sample_2_Fashion_Guy.xlsx\ -\ Highlighted.csv \
    /data/ebay/notebooks/olivyatan/Gen_signals/Sample_2_Fashion_Yonatan.xlsx\ -\ Highlighted.csv \
    /data/ebay/notebooks/olivyatan/Gen_signals/Sample_2_Fashion_Gilad.xlsx\ -\ Highlighted.csv \
    /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_3_020325_fashion_pairs/

In [8]:
!ls /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_3_020325_fashion_pairs/

'Sample_2_Fashion_Gilad.xlsx - Highlighted.csv'
'Sample_2_Fashion_Guy.xlsx - Highlighted.csv'
'Sample_2_Fashion_Matan.xlsx - Highlighted.csv'
'Sample_2_Fashion_Yonatan.xlsx - Highlighted.csv'

In [ ]:
!cd /data/ebay/notebooks/olivyatan/Gen_signals/

In [96]:
!ls /data/ebay/data/olivyatan/Datasets/annotation_files/

aggregated_disagreement_annotations.xlsx  tagging_2_020225_HG_pairs

In [24]:
1# Define annotator pairs to compare
annotator_pairs = [('Yonatan', 'Guy'), ('Ortal', 'Yotam'), ('Tal', 'Matan')]

In [117]:
### files were download as csv from google sheets to avoid formulas of drop downs manually.

### Analyse annotations

In [118]:
file_path = "/data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_HG_pairs/highlighted_text_filtered_by_heuristic_sample-HG_Yotam.xlsx - Highlighted.csv"

df = pd.read_csv(file_path)

In [119]:
df.head(2)

,item_id,gen_sig_gpt,annotator_name,label,reason,comment,title,aspects,desc,match_type,match_column
0,166886207661,Alleviates Knee Pressure,Yotam,2.0,NaN,special feature of the stool,"meditation bench - foldable, ergonomic, bamboo...","{'assembly required': 'no', 'core_product_type...",Menu Other Items Feedbacks About Us Contact Us...,exact,desc
1,395493192780,Sweetened With Monk Fruit,Yotam,2.0,NaN,NaN,choczero sugar free caramels keto candy all ...,"{'brand': 'choczero', 'flavor': 'candy', 'food...",ChocZero Sugar Free Caramels - Keto Candy - Al...,exact,desc

In [1]:
import openpyxl

In [20]:
!ls /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs/tagged_data

'highlighted_text_filtered_by_heuristic_sample-Fashion_Dimitri.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Gilad.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Guy.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Matan.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Ortal.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Tal.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Yonatan.xlsx - Highlighted.csv'
'highlighted_text_filtered_by_heuristic_sample-Fashion_Yotam.xlsx - Highlighted.csv'

#### Load results of annnotations and Create annotation_dfs

In [15]:
import pandas as pd
import os

# Define file paths and corresponding DataFrame names
annotation_folder = "/data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs/tagged_data"
file_names = [
    # "highlighted_text_filtered_by_heuristic_sample-Fashion_Dimitri.xlsx - Highlighted.csv",
    #"highlighted_text_filtered_by_heuristic_sample-Fashion_Gilad.xlsx - Highlighted.csv",
    "highlighted_text_filtered_by_heuristic_sample-Fashion_Guy.xlsx - Highlighted.csv",
    "highlighted_text_filtered_by_heuristic_sample-Fashion_Matan.xlsx - Highlighted.csv",
    "highlighted_text_filtered_by_heuristic_sample-Fashion_Ortal.xlsx - Highlighted.csv",
    "highlighted_text_filtered_by_heuristic_sample-Fashion_Tal.xlsx - Highlighted.csv",
    "highlighted_text_filtered_by_heuristic_sample-Fashion_Yonatan.xlsx - Highlighted.csv",
    "highlighted_text_filtered_by_heuristic_sample-Fashion_Yotam.xlsx - Highlighted.csv"
]

# Define annotator names corresponding to the files
annotator_names = ["guy", "matan", "ortal", "tal", "yonatan", "yotam"]

# Dictionary to store DataFrames
annotation_dfs = {}

# Loop through files and read them into DataFrames
for file_name, annotator_name in zip(file_names, annotator_names):
    file_path = os.path.join(annotation_folder, file_name)
    
    try:
        # Read the file into a DataFrame
        df = pd.read_csv(file_path)
        
        # Store the DataFrame in the dictionary with a descriptive name
        annotation_dfs[f"{annotator_name}_annotation_df"] = df
        
        print(f"Successfully loaded {annotator_name}_annotation_df with {len(df)} rows.")
    except Exception as e:
        print(f"Error loading {file_name}: {e}")

# Access individual DataFrames by their variable name
yonatan_annotation_df = annotation_dfs.get("yonatan_annotation_df")
guy_annotation_df = annotation_dfs.get("guy_annotation_df")
matan_annotation_df = annotation_dfs.get("matan_annotation_df")
ortal_annotation_df = annotation_dfs.get("ortal_annotation_df")
tal_annotation_df = annotation_dfs.get("tal_annotation_df")
yotam_annotation_df = annotation_dfs.get("yotam_annotation_df")

Successfully loaded guy_annotation_df with 100 rows.
Successfully loaded matan_annotation_df with 100 rows.
Successfully loaded ortal_annotation_df with 100 rows.
Successfully loaded tal_annotation_df with 105 rows.
Successfully loaded yonatan_annotation_df with 107 rows.
Successfully loaded yotam_annotation_df with 100 rows.

In [16]:
# List of DataFrames to modify
annotation_dfs_list = [
    "yonatan_annotation_df",
    "guy_annotation_df",
    "matan_annotation_df",
    "ortal_annotation_df",
    "tal_annotation_df",
    "yotam_annotation_df"
]

# Convert 'item_id' column to integer in each DataFrame
for df_name in annotation_dfs_list:
    df = annotation_dfs.get(df_name)  # Get the DataFrame
    if df is not None and "item_id" in df.columns:  # Ensure DataFrame exists and has 'item_id' column
        df["item_id"] = (
            df["item_id"]
            .astype(str)  # Convert everything to a string
            .str.replace(r"\.0$", "", regex=True)  # Remove trailing .0
            .replace("nan", "0")  # Replace 'nan' strings with '0'
            .fillna(0)  # Ensure NaN values are replaced with 0
            .astype(int)  # Convert to integer
        )

In [17]:
tal_annotation_df.head(2)

,item_id,gen_sig_gpt,annotator_name,label,reason,comment,title,aspects,desc,match_type,match_column
0,167245009030,5-Pocket Design,Tal,1,NaN,NaN,levis 501 men's straight leg button fly med bl...,"{'absorbency': None, 'accents': 'button', 'acc...",*Item size may differ from what is pictured on...,exact,aspects
1,167245009030,100% Cotton Denim,Tal,1,NaN,NaN,levis 501 men's straight leg button fly med bl...,"{'absorbency': None, 'accents': 'button', 'acc...",*Item size may differ from what is pictured on...,exact,desc

In [18]:
yonatan_annotation_df.head(2)

,item_id,gen_sig_gpt,annotator_name,label,reason,comment,title,aspects,desc,match_type,match_column
0,167245009030,5-Pocket Design,Yonatan,1.0,NaN,NaN,levis 501 men's straight leg button fly med bl...,"{'absorbency': None, 'accents': 'button', 'acc...",*Item size may differ from what is pictured on...,exact,aspects
1,167245009030,100% Cotton Denim,Yonatan,2.0,NaN,NaN,levis 501 men's straight leg button fly med bl...,"{'absorbency': None, 'accents': 'button', 'acc...",*Item size may differ from what is pictured on...,exact,desc

In [19]:
yonatan_annotation_df['item_id'].head(2)

0    167245009030
1    167245009030
Name: item_id, dtype: int64

In [20]:
annotator_pairs = [('Ortal', 'Matan'), ('Tal', 'Yonatan'), ('Guy', 'Yotam')]

In [25]:
    joined_df = pd.merge(
        matan_annotation_df,
        tal_annotation_df,
        on=['item_id','gen_sig_gpt'],
        how='inner',
        suffixes=('', '_yonatan')  # Add suffix to overlapping column names
    )

In [26]:
joined_df.shape

(0, 20)

In [142]:
joined_df.head(5)

,item_id,gen_sig_gpt,annotator_name,label,reason,comment,title,aspects,desc,match_type,...,gen_sig_gpt_yonatan,annotator_name_yonatan,label_yonatan,reason_yonatan,comment_yonatan,title_yonatan,aspects_yonatan,desc_yonatan,match_type_yonatan,match_column_yonatan
0,266966172972,High Quality Stainless Steel,Guy,2,NaN,NaN,48pcs/set gold cutlery set dinnerware tablewar...,"{'brand': 'unbranded', 'color': 'gold', 'core_...",modname=ckeditor Product information Made of H...,exact,...,High Quality Stainless Steel,Yonatan,2,NaN,NaN,48pcs/set gold cutlery set dinnerware tablewar...,"{'brand': 'unbranded', 'color': 'gold', 'core_...",modname=ckeditor Product information Made of H...,exact,desc
1,184145394657,Compatible Brand,Guy,0,NaN,compatible to what ?,whirlpool washer timer 385341,"{'Brand': 'whirlpool', 'capacity': '15 lb', 'c...",Whirlpool Washer Timer 385341. AS PICTURED.PLE...,exact,...,Compatible Brand,Yonatan,0,Off-Topic,aspect name and note value,whirlpool washer timer 385341,"{'Brand': 'whirlpool', 'capacity': '15 lb', 'c...",Whirlpool Washer Timer 385341. AS PICTURED.PLE...,exact,aspects
2,387328646703,Independently Rotating Shelves,Guy,1,NaN,NaN,rev-a-shelf ld-4bw-262-28-1 lazy daisy wood 2-...,"{'additional parts required': 'no', 'assembly ...",Powered by Frooition Top Products Kitchen Bath...,ngram+non ngram,...,Independently Rotating Shelves,Yonatan,1,NaN,NaN,rev-a-shelf ld-4bw-262-28-1 lazy daisy wood 2-...,"{'additional parts required': 'no', 'assembly ...",Powered by Frooition Top Products Kitchen Bath...,ngram+non ngram,desc
3,226260681725,100% Cotton Material,Guy,1,NaN,NaN,kinetic geometrics Cotton fabric henry glass ...,"{'brand': 'henry glass & co.', 'color': 'purpl...",Kinetic Geometric Henry Glass Fabrics 45 Inche...,exact,...,100% Cotton Material,Yonatan,2,NaN,NaN,kinetic geometrics Cotton fabric henry glass ...,"{'brand': 'henry glass & co.', 'color': 'purpl...",Kinetic Geometric Henry Glass Fabrics 45 Inche...,exact,desc
4,254880218364,304 Stainless Steel,Guy,1,NaN,NaN,"(10) fit tube o/d 3-25mm 1/8""-1/2"" 304 Stainle...",{'core_product_type': 'plumbing and fixtures'},Detail Material:304 Stainless Steel Fit For Tu...,exact,...,304 Stainless Steel,Yonatan,1,NaN,NaN,"(10) fit tube o/d 3-25mm 1/8""-1/2"" 304 Stainle...",{'core_product_type': 'plumbing and fixtures'},Detail Material:304 Stainless Steel Fit For Tu...,exact,desc

#### Join results of anotator pairs:

In [21]:
import pandas as pd

def join_and_aggregate_pairs(annotation_dfs, annotator_pairs):
    """Join annotation DataFrames by pairs and return an aggregated DataFrame."""
    aggregated_df = pd.DataFrame()

    for annotator_1, annotator_2 in annotator_pairs:
        # Get the DataFrames for each annotator
        df1 = annotation_dfs.get(f"{annotator_1.lower()}_annotation_df")
        df2 = annotation_dfs.get(f"{annotator_2.lower()}_annotation_df")
        
        if df1 is not None and df2 is not None:
            # Ensure 'item_id' column is of the same type in both DataFrames
            df1['item_id'] = df1['item_id'].astype(str)
            df2['item_id'] = df2['item_id'].astype(str)

            # Rename columns in df2 to avoid conflicts
            df2 = df2.rename(columns={
                'annotator_name': 'annotator_name_2',
                'label': 'label_2',
                'reason': 'reason_2',
                'comment': 'comment_2'
            })
            
            # Join the two DataFrames on 'item_id'
            merged_df = pd.merge(df1, df2, on=['item_id','gen_sig_gpt'], how='inner')
            
            merged_df = merged_df.rename(columns={'title_x': 'title', 'aspects_x': 'aspects', 'desc_x': 'desc',
            'match_type_x': 'match_type', 'match_column_x': 'match_column'
            })

            # Select and reorder the required columns
            merged_df = merged_df[[
            'item_id', 'gen_sig_gpt', 'annotator_name', 'label', 'reason', 'comment',
            'annotator_name_2', 'label_2', 'reason_2', 'comment_2',
            'title', 'aspects', 'desc', 'match_type', 'match_column'
            ]]
            
            # Append the result to the aggregated DataFrame
            aggregated_df = pd.concat([aggregated_df, merged_df], ignore_index=True)

    return aggregated_df


# Example usage
annotator_pairs = [('Ortal', 'Matan'), ('Tal', 'Yonatan'), ('Guy', 'Yotam')]
output_df = join_and_aggregate_pairs(annotation_dfs, annotator_pairs)

In [22]:
output_df.shape

(305, 15)

In [63]:
1

1

In [23]:
output_df.head(5)

,item_id,gen_sig_gpt,annotator_name,label,reason,comment,annotator_name_2,label_2,reason_2,comment_2,title,aspects,desc,match_type,match_column
0,256802207440,Refreshing Blue Hue,Ortal,1.0,NaN,NaN,Matan,1.0,NaN,NaN,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc
1,256802207440,Regular Fit,Ortal,1.0,NaN,NaN,Matan,1.0,NaN,NaN,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc
2,256802207440,Long Sleeves,Ortal,1.0,NaN,NaN,Matan,0.0,NaN,Seems not informative. Probably discernable fr...,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc
3,256802207440,Durability,Ortal,0.0,Not Clear,NaN,Matan,1.0,NaN,NaN,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc
4,256802207440,Effortless Sophistication,Ortal,1.0,NaN,NaN,Matan,2.0,NaN,NaN,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc

#### Save pairs tagged data :

In [24]:
output_df.to_parquet("/data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs/tagged_data/pairs_tagged_Fashion_1_feb25_agg")

In [25]:
disagree_df = output_df[output_df['label'] != output_df['label_2']]

In [26]:
disagree_df.shape

(140, 15)

In [27]:
disagree_df = output_df[output_df['label'] != output_df['label_2']].copy()

# Define disagreement groups to ensure symmetrical comparison (e.g., (0,1) is same as (1,0))
disagree_df['disagreement_type'] = disagree_df.apply(lambda row: tuple(sorted([row['label'], row['label_2']])), axis=1)

# Count occurrences of each disagreement type
disagree_counts = disagree_df['disagreement_type'].value_counts().reset_index()
disagree_counts.columns = ['Disagreement Type', 'Count']

# Calculate total number of disagreements
total_disagreements = len(disagree_df)

# Calculate percentages (rounded to 1 decimal place)
disagree_counts['Percentage'] = (disagree_counts['Count'] / total_disagreements * 100).round(0)

# Print results
print(disagree_counts)

  Disagreement Type  Count  Percentage
0        (1.0, 2.0)     72        51.0
1        (0.0, 1.0)     55        39.0
2        (0.0, 2.0)     10         7.0
3        (1.0, nan)      1         1.0
4        (0.0, nan)      1         1.0
5        (nan, 1.0)      1         1.0

In [68]:
# Create a copy of disagreement cases
disagree_df = output_df[output_df['label'] != output_df['label_2']].copy()

# Define disagreement groups to ensure symmetrical comparison (e.g., (0,1) is same as (1,0))
disagree_df['disagreement_type'] = disagree_df.apply(lambda row: tuple(sorted([row['label'], row['label_2']])), axis=1)

# Identify annotator pairs
disagree_df['annotator_pair'] = disagree_df.apply(lambda row: tuple(sorted([row['annotator_name'], row['annotator_name_2']])), axis=1)

# Count occurrences of each disagreement type per annotator pair
disagree_counts_by_pair = disagree_df.groupby(['annotator_pair', 'disagreement_type']).size().reset_index(name='Count')

# Calculate total disagreements per pair
total_disagreements_by_pair = disagree_df.groupby('annotator_pair').size().reset_index(name='Total Disagreements')

# Merge total disagreements to calculate percentages
disagree_counts_by_pair = disagree_counts_by_pair.merge(total_disagreements_by_pair, on='annotator_pair')

# Calculate percentages (rounded to 1 decimal place)
disagree_counts_by_pair['Percentage'] = (disagree_counts_by_pair['Count'] / disagree_counts_by_pair['Total Disagreements'] * 100).round(1)

# Print results
print(disagree_counts_by_pair)

    annotator_pair disagreement_type  Count  Total Disagreements  Percentage
0     (Guy, Yotam)        (0.0, 1.0)     18                   51        35.3
1     (Guy, Yotam)        (0.0, 2.0)      8                   51        15.7
2     (Guy, Yotam)        (1.0, 2.0)     24                   51        47.1
3     (Guy, Yotam)        (nan, 1.0)      1                   51         2.0
4   (Matan, Ortal)        (0.0, 1.0)     13                   27        48.1
5   (Matan, Ortal)        (0.0, nan)      1                   27         3.7
6   (Matan, Ortal)        (1.0, 2.0)     12                   27        44.4
7   (Matan, Ortal)        (1.0, nan)      1                   27         3.7
8   (Tal, Yonatan)        (0.0, 1.0)     24                   62        38.7
9   (Tal, Yonatan)        (0.0, 2.0)      2                   62         3.2
10  (Tal, Yonatan)        (1.0, 2.0)     36                   62        58.1

In [80]:
from sklearn.metrics import cohen_kappa_score


# List to store kappa scores
kappa_scores = []

# Compute Cohen's Kappa for each unique annotator pair
for pair in output_df[['annotator_name', 'annotator_name_2']].drop_duplicates().itertuples(index=False):
    # Filter data for this annotator pair
    pair_df = output_df[
        ((output_df['annotator_name'] == pair[0]) & (output_df['annotator_name_2'] == pair[1])) |
        ((output_df['annotator_name'] == pair[1]) & (output_df['annotator_name_2'] == pair[0]))
    ]
    
    if not pair_df.empty:
        # Drop NaN values to prevent errors
        valid_df = pair_df[['label', 'label_2']].dropna()

        if not valid_df.empty:
            kappa = cohen_kappa_score(valid_df['label'], valid_df['label_2'])
        else:
            kappa = None  # No valid data for this pair
    else:
        kappa = None  # No data for this pair

    kappa_scores.append({'annotator_pair': pair, 'Cohen_Kappa': kappa})

# Convert to DataFrame
kappa_df = pd.DataFrame(kappa_scores)

# Print Kappa scores per annotator pair
print(kappa_df)

   annotator_pair  Cohen_Kappa
0  (Ortal, Matan)     0.473345
1  (Tal, Yonatan)     0.009132
2    (Guy, Yotam)     0.247263

In [179]:
!pwd

/data/ebay/data/olivyatan/Datasets

In [70]:
!ls /data/ebay/data/olivyatan/Datasets/annotation_files/

tagging_2_020225_HG_pairs  tagging_2_020225_fashion_pairs

#### Sava pairs of all data and disagree

In [71]:
parquet_path = "/data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs/df_all_305_fashion_feb25.parquet"

# Save as Parquet
output_df.to_parquet(parquet_path, index=False)

print(f"File saved successfully at: {parquet_path}")

File saved successfully at: /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs/df_all_305_fashion_feb25.parquet

In [78]:
# Save the DataFrame with highlighted text in Excel
# Define the base path and the file name
base_path = '/data/ebay/notebooks/olivyatan/Gen_signals'
file_name = 'fashion_disagree_df_#2_020225_pairs.xlsx' 
# Construct the full path
output_excel_path = os.path.join(base_path, file_name) 

highlight_text_to_xsl(
    df=disagree_df, 
    gensig_colname="gen_sig_gpt", 
    source_colnames=["title", "aspects", "desc"], 
    output_excelfile_path=output_excel_path,
    dropdown_config=None
)

100%|██████████| 140/140 [00:00<00:00, 877.39it/s]

Excel file with dropdowns saved to /data/ebay/notebooks/olivyatan/Gen_signals/fashion_disagree_df_#2_020225_pairs.xlsx.

In [29]:
df_final_disagree.head(1)

,item_id,gen_sig_gpt,Final Label,comment,annotator_name,label,reason,comment.1,annotator_name_2,label_2,reason_2,comment_2,title,aspects,desc,match_type,match_column,disagreement_type,annotator_pair
0,2.262610e+11,100% Cotton Material,1.0,NaN,Yonatan,2.0,NaN,NaN,Guy,1,NaN,NaN,kinetic geometrics Cotton fabric henry glass ...,"{'brand': 'henry glass & co.', 'color': 'purpl...",Kinetic Geometric Henry Glass Fabrics 45 Inche...,exact,desc,"(1, 2.0)","('Guy', 'Yonatan')"

In [26]:
df_final_disagree.columns

Index(['item_id', 'gen_sig_gpt', 'Final Label', 'comment', 'annotator_name',
       'label', 'reason', 'comment.1', 'annotator_name_2', 'label_2',
       'reason_2', 'comment_2', 'title', 'aspects', 'desc', 'match_type',
       'match_column', 'disagreement_type', 'annotator_pair'],
      dtype='object')

In [27]:
df_final_disagree.shape

(80, 19)

In [31]:
output_df.columns

Index(['item_id', 'gen_sig_gpt', 'annotator_name', 'label', 'reason',
       'comment', 'annotator_name_2', 'label_2', 'reason_2', 'comment_2',
       'title', 'aspects', 'desc', 'match_type', 'match_column'],
      dtype='object')

In [30]:
output_df.head(1)

,item_id,gen_sig_gpt,annotator_name,label,reason,comment,annotator_name_2,label_2,reason_2,comment_2,title,aspects,desc,match_type,match_column
0,266966172972,High Quality Stainless Steel,Yonatan,2.0,NaN,NaN,Guy,2,NaN,NaN,48pcs/set gold cutlery set dinnerware tablewar...,"{'brand': 'unbranded', 'color': 'gold', 'core_...",modname=ckeditor Product information Made of H...,exact,desc

In [40]:
import pandas as pd

def join_with_final_disagree(output_df, df_final_disagree):
    """
    Joins output_df with df_final_disagree on ['item_id', 'gen_sig_gpt']
    and adds 'final_label', 'final_reason', 'final_comment' based on available values.

    - Ensures correct column naming even if suffixes (`_o`, `_d`) are added after join.
    - Prioritizes `df_final_disagree` values but falls back to `output_df` if missing.
    """

    # Ensure the join keys have matching dtypes
    output_df['item_id'] = output_df['item_id'].astype(str)
    output_df['gen_sig_gpt'] = output_df['gen_sig_gpt'].astype(str)
    df_final_disagree['item_id'] = df_final_disagree['item_id'].astype(str)
    df_final_disagree['gen_sig_gpt'] = df_final_disagree['gen_sig_gpt'].astype(str)

    # Perform a left join with suffixes
    joined_df = output_df.merge(df_final_disagree, on=['item_id', 'gen_sig_gpt'], how='left', suffixes=('_o', '_d'))

    # Creating final_label: Take from 'Final Label' if available, otherwise use 'label_o'
    joined_df['final_label'] = joined_df['final_label'].combine_first(joined_df['label_o'])

    # Creating final_reason: priority order → reason_d > reason_o > reason_2_o > reason_2_d
    joined_df['final_reason'] = joined_df[['final_reason','reason_d', 'reason_o', 'reason_2_o', 'reason_2_d']].bfill(axis=1).iloc[:, 0]

    # Creating final_comment: priority order → comment_d > comment_o > comment_2_o > comment_2_d
    joined_df['final_comment'] = joined_df[['final_comment','comment_d', 'comment_o', 'comment_2_o', 'comment_2_d']].bfill(axis=1).iloc[:, 0]

    # Define the required columns from output_df to retain
    required_columns = [
        'annotator_name', 'label', 'reason', 'comment', 'annotator_name_2', 'label_2',
        'reason_2', 'comment_2', 'title', 'aspects', 'desc', 'match_type', 'match_column'
    ]

    # Ensure correct column naming after merging (handle suffix issues)
    corrected_columns = []
    for col in required_columns:
        if f"{col}_o" in joined_df.columns:  # Keep original from output_df
            corrected_columns.append(f"{col}_o")
        elif f"{col}_d" in joined_df.columns:  # If missing, try from df_final_disagree
            corrected_columns.append(f"{col}_d")

    # Rename back to expected names (remove `_o` and `_d` suffixes)
    rename_dict = {col: col.replace('_o', '').replace('_d', '') for col in corrected_columns}
    joined_df = joined_df.rename(columns=rename_dict)

    # Final column selection: Put final_* columns after 'item_id' and 'gen_sig_gpt', followed by other columns from output_df
    selected_columns = ['item_id', 'gen_sig_gpt', 'final_label', 'final_reason', 'final_comment'] + list(rename_dict.values())

    return joined_df[selected_columns]

# Now apply the function
df_final_all_fashion_feb25 = join_with_final_disagree(output_df, df_final_disagree)


#### Join disagree with agree for all data pairs tagged

In [35]:
# Ensure the join keys have matching dtypes
output_df['item_id'] = output_df['item_id'].astype(str)
output_df['gen_sig_gpt'] = output_df['gen_sig_gpt'].astype(str)
df_final_disagree['item_id'] = df_final_disagree['item_id'].astype(str)
df_final_disagree['gen_sig_gpt'] = df_final_disagree['gen_sig_gpt'].astype(str)

joined_df = output_df.merge(df_final_disagree, on=['item_id', 'gen_sig_gpt'], how='left', suffixes=('_o', '_d'))

In [38]:
joined_df.head(3)

,item_id,gen_sig_gpt,annotator_name_o,label_o,reason_o,comment_o,annotator_name_2_o,label_2_o,reason_2_o,comment_2_o,...,annotator_name_2_d,label_2_d,reason_2_d,comment_2_d,title_d,aspects_d,desc_d,match_type_d,match_column_d,annotator_pair
0,256802207440,Refreshing Blue Hue,Ortal,1.0,NaN,NaN,Matan,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,256802207440,Regular Fit,Ortal,1.0,NaN,NaN,Matan,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,256802207440,Long Sleeves,Ortal,1.0,NaN,NaN,Matan,0.0,NaN,Seems not informative. Probably discernable fr...,...,Matan,0.0,NaN,Seems not informative. Probably discernable fr...,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc,"('Matan', 'Ortal')"

In [39]:
joined_df.columns

Index(['item_id', 'gen_sig_gpt', 'annotator_name_o', 'label_o', 'reason_o',
       'comment_o', 'annotator_name_2_o', 'label_2_o', 'reason_2_o',
       'comment_2_o', 'title_o', 'aspects_o', 'desc_o', 'match_type_o',
       'match_column_o', 'final_label', 'final_reason', 'final_comment',
       'ask:', 'annotator_name_d', 'label_d', 'reason_d', 'comment_d',
       'annotator_name_2_d', 'label_2_d', 'reason_2_d', 'comment_2_d',
       'title_d', 'aspects_d', 'desc_d', 'match_type_d', 'match_column_d',
       'annotator_pair'],
      dtype='object')

In [33]:
current_columns = ['item_id', 'gen_sig_gpt', 'annotator_name_o', 'label_o', 'reason_o',
                   'comment_o', 'annotator_name_2_o', 'label_2_o', 'reason_2_o',
                   'comment_2_o', 'title_o', 'aspects_o', 'desc_o', 'match_type_o',
                   'match_column_o', 'final_label', 'final_reason', 'final_comment',
                   'ask:', 'annotator_name_d', 'label_d', 'reason_d', 'comment_d',
                   'annotator_name_2_d', 'label_2_d', 'reason_2_d', 'comment_2_d',
                   'title_d', 'aspects_d', 'desc_d', 'match_type_d', 'match_column_d',
                   'annotator_pair']

# Desired order with selected columns first
selected_columns = ['item_id', 'gen_sig_gpt', 'final_label', 'final_reason', 'final_comment']
other_columns = [col for col in current_columns if col not in selected_columns]
renamed_columns = selected_columns + other_columns

# Reordering the DataFrame
joined_df = joined_df[renamed_columns]

In [34]:
joined_df

,item_id,gen_sig_gpt,final_label,final_reason,final_comment,annotator_name_o,label_o,reason_o,comment_o,annotator_name_2_o,...,annotator_name_2_d,label_2_d,reason_2_d,comment_2_d,title_d,aspects_d,desc_d,match_type_d,match_column_d,annotator_pair
0,256802207440,Refreshing Blue Hue,NaN,NaN,NaN,Ortal,1.0,NaN,NaN,Matan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,256802207440,Regular Fit,NaN,NaN,NaN,Ortal,1.0,NaN,NaN,Matan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,256802207440,Long Sleeves,0.0,obvious from the image,Should be obvious from the image,Ortal,1.0,NaN,NaN,Matan,...,Matan,0.0,NaN,Seems not informative. Probably discernable fr...,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc,"('Matan', 'Ortal')"
3,256802207440,Durability,0.0,Not clear- incorrect grammer,NaN,Ortal,0.0,Not Clear,NaN,Matan,...,Matan,1.0,NaN,NaN,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc,"('Matan', 'Ortal')"
4,256802207440,Effortless Sophistication,2.0,NaN,NaN,Ortal,1.0,NaN,NaN,Matan,...,Matan,2.0,NaN,NaN,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc,"('Matan', 'Ortal')"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,235909747392,Short Sleeve,0.0,Obvious from picture,NaN,Guy,0.0,NaN,obvious,Yotam,...,Yotam,1.0,NaN,NaN,superman mens red shirt size xl,"{'absorbency': None, 'accents': None, 'accesso...",Very good condition Shirt measures 22 inches a...,exact,aspects,"('Guy', 'Yotam')"
301,404972097668,Lightweight Design,2.0,NaN,NaN,Guy,1.0,NaN,NaN,Yotam,...,Yotam,2.0,NaN,NaN,"nwob bzees women's slip on sneakers, dark gre...","{'absorbency': None, 'accents': 'logo', 'acces...",Elevate your casual look with these stylish Bz...,exact,desc,"('Guy', 'Yotam')"
302,404972097668,Moderate Cushioning,1.0,NaN,NaN,Guy,1.0,NaN,NaN,Yotam,...,Yotam,2.0,NaN,NaN,"nwob bzees women's slip on sneakers, dark gre...","{'absorbency': None, 'accents': 'logo', 'acces...",Elevate your casual look with these stylish Bz...,exact,desc,"('Guy', 'Yotam')"
303,404972097668,Slip-On Closure,1.0,NaN,NaN,Guy,1.0,NaN,NaN,Yotam,...,Yotam,2.0,NaN,NaN,"nwob bzees women's slip on sneakers, dark gre...","{'absorbency': None, 'accents': 'logo', 'acces...",Elevate your casual look with these stylish Bz...,exact,desc,"('Guy', 'Yotam')"
304,404972097668,Striped Pattern,1.0,NaN,NaN,Guy,NaN,NaN,NaN,Yotam,...,Yotam,1.0,NaN,NaN,"nwob bzees women's slip on sneakers, dark gre...","{'absorbency': None, 'accents': 'logo', 'acces...",Elevate your casual look with these stylish Bz...,exact,aspects,"('Guy', 'Yotam')"

In [41]:
df_final_all_fashion_feb25.shape

(305, 18)

In [43]:
df_final_all_fashion_feb25.columns

Index(['item_id', 'gen_sig_gpt', 'final_label', 'final_reason',
       'final_comment', 'annotator_name', 'label', 'reason', 'comment',
       'annotator_name_2', 'label_2', 'reason_2', 'comment_2', 'title',
       'aspects', 'desc', 'match_type', 'match_column'],
      dtype='object')

#### Dis/agreements data:

In [45]:
df_final_all_fashion_feb25

,item_id,gen_sig_gpt,final_label,final_reason,final_comment,annotator_name,label,reason,comment,annotator_name_2,label_2,reason_2,comment_2,title,aspects,desc,match_type,match_column
0,256802207440,Refreshing Blue Hue,1.0,NaN,NaN,Ortal,1.0,NaN,NaN,Matan,1.0,NaN,NaN,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc
1,256802207440,Regular Fit,1.0,NaN,NaN,Ortal,1.0,NaN,NaN,Matan,1.0,NaN,NaN,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc
2,256802207440,Long Sleeves,0.0,obvious from the image,Should be obvious from the image,Ortal,1.0,NaN,NaN,Matan,0.0,NaN,Seems not informative. Probably discernable fr...,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc
3,256802207440,Durability,0.0,Not clear- incorrect grammer,NaN,Ortal,0.0,Not Clear,NaN,Matan,1.0,NaN,NaN,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc
4,256802207440,Effortless Sophistication,2.0,NaN,NaN,Ortal,1.0,NaN,NaN,Matan,2.0,NaN,NaN,men’s fiji shirt size 3xl,"{'absorbency': None, 'accents': None, 'accesso...",Experience comfort and style with the Men's Fi...,exact,desc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,235909747392,Short Sleeve,0.0,Obvious from picture,obvious,Guy,0.0,NaN,obvious,Yotam,1.0,NaN,NaN,superman mens red shirt size xl,"{'absorbency': None, 'accents': None, 'accesso...",Very good condition Shirt measures 22 inches a...,exact,aspects
301,404972097668,Lightweight Design,2.0,NaN,NaN,Guy,1.0,NaN,NaN,Yotam,2.0,NaN,NaN,"nwob bzees women's slip on sneakers, dark gre...","{'absorbency': None, 'accents': 'logo', 'acces...",Elevate your casual look with these stylish Bz...,exact,desc
302,404972097668,Moderate Cushioning,1.0,NaN,NaN,Guy,1.0,NaN,NaN,Yotam,2.0,NaN,NaN,"nwob bzees women's slip on sneakers, dark gre...","{'absorbency': None, 'accents': 'logo', 'acces...",Elevate your casual look with these stylish Bz...,exact,desc
303,404972097668,Slip-On Closure,1.0,NaN,NaN,Guy,1.0,NaN,NaN,Yotam,2.0,NaN,NaN,"nwob bzees women's slip on sneakers, dark gre...","{'absorbency': None, 'accents': 'logo', 'acces...",Elevate your casual look with these stylish Bz...,exact,desc
304,404972097668,Striped Pattern,1.0,NaN,NaN,Guy,NaN,NaN,NaN,Yotam,1.0,NaN,NaN,"nwob bzees women's slip on sneakers, dark gre...","{'absorbency': None, 'accents': 'logo', 'acces...",Elevate your casual look with these stylish Bz...,exact,aspects

In [46]:
base_path = '/data/ebay/notebooks/olivyatan/Gen_signals'
file_name = 'final_label_all_305_df_2_020225_pairs_fashion.xlsx' 
# Construct the full path
output_excel_path = os.path.join(base_path, file_name) 

highlight_text_to_xsl(
    df=df_final_all_fashion_feb25, 
    gensig_colname="gen_sig_gpt", 
    source_colnames=["title", "aspects", "desc"], 
    output_excelfile_path=output_excel_path,
    dropdown_config=None
)

100%|██████████| 305/305 [00:00<00:00, 903.44it/s]

Excel file with dropdowns saved to /data/ebay/notebooks/olivyatan/Gen_signals/final_label_all_305_df_2_020225_pairs_fashion.xlsx.

In [47]:
!ls /data/ebay/data/olivyatan/Datasets/annotation_files/

tagging_2_020225_HG_pairs  tagging_2_020225_fashion_pairs

In [48]:
# Define the file path
parquet_path = "/data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs/df_final_all_fashion_feb25_1.parquet"

# Save as Parquet
df_final_all_fashion_feb25.to_parquet(parquet_path, index=False)

print(f"File saved successfully at: {parquet_path}")

File saved successfully at: /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs/df_final_all_fashion_feb25_1.parquet

In [49]:
mv /data/ebay/notebooks/olivyatan/Gen_signals/final_label_all_305_df_2_020225_pairs_fashion.xlsx /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs/

In [50]:
!ls /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_2_020225_fashion_pairs/

df_all_305_fashion_feb25.parquet
df_final_all_fashion_feb25_1.parquet
final_label_all_305_df_2_020225_pairs_fashion.xlsx
highlighted_text_filtered_by_heuristic_sample-Fashion_Dimitri.xlsx
highlighted_text_filtered_by_heuristic_sample-Fashion_Gilad.xlsx
highlighted_text_filtered_by_heuristic_sample-Fashion_Guy.xlsx
highlighted_text_filtered_by_heuristic_sample-Fashion_Matan.xlsx
highlighted_text_filtered_by_heuristic_sample-Fashion_Ortal.xlsx
highlighted_text_filtered_by_heuristic_sample-Fashion_Tal.xlsx
highlighted_text_filtered_by_heuristic_sample-Fashion_Yonatan.xlsx
highlighted_text_filtered_by_heuristic_sample-Fashion_Yotam.xlsx
tagged_data

#### Concat Fashion Data of second fashion annotation:

In [10]:
import pandas as pd
import os

# Define source directory
csv_dir = "/data/ebay/data/olivyatan/Datasets/annotation_files/tagging_3_020325_fashion_pairs"

# List the target CSV files
filenames = [
    "Sample_2_Fashion_Matan.xlsx - Highlighted.csv",
    "Sample_2_Fashion_Guy.xlsx - Highlighted.csv",
    "Sample_2_Fashion_Yonatan.xlsx - Highlighted.csv",
    "Sample_2_Fashion_Gilad.xlsx - Highlighted.csv",
]

# Load and concatenate
df_list = []
for fname in filenames:
    path = os.path.join(csv_dir, fname)
    df = pd.read_csv(path)
    df["source_file"] = fname  # optionally track the source
    df_list.append(df)

df_concat = pd.concat(df_list, ignore_index=True)
df_concat['item_id'] = df_concat['item_id'].astype(str) 
# Save as Parquet
out_path = os.path.join(csv_dir, "fashion_2_020325_tagging_combined_4Unique.parquet")
df_concat.to_parquet(out_path, index=False)

print(f"✅ Combined and saved to {out_path}")

✅ Combined and saved to /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_3_020325_fashion_pairs/fashion_2_020325_tagging_combined_4Unique.parquet

In [12]:
df_concat.shape

(364, 13)

In [ ]:
/data/ebay/data/olivyatan/Datasets/annotation_files/tagging_3_020325_fashion_pairs/fashion_2_020325_tagging_combined_4Unique.parquet

In [15]:
csv_out_path = "/data/ebay/notebooks/olivyatan/Gen_signals/fashion_2_020325_tagging_combined_4Unique.csv"
df_concat.to_csv(csv_out_path, index=False)

In [19]:
!cp '/data/ebay/notebooks/olivyatan/Gen_signals/fashion_2_020325_tagging_combined_4Unique_filled.csv' /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_3_020325_fashion_pairs/

In [22]:
!ls /data/ebay/data/olivyatan/Datasets/annotation_files/tagging_3_020325_fashion_pairs/

'Sample_2_Fashion_Gilad.xlsx - Highlighted.csv'
'Sample_2_Fashion_Guy.xlsx - Highlighted.csv'
'Sample_2_Fashion_Matan.xlsx - Highlighted.csv'
'Sample_2_Fashion_Yonatan.xlsx - Highlighted.csv'
 fashion_2_020325_tagging_combined_4Unique.csv
 fashion_2_020325_tagging_combined_4Unique.parquet
 fashion_2_020325_tagging_combined_4Unique_filled.csv

In [21]:
csv_path = '/data/ebay/notebooks/olivyatan/Gen_signals/fashion_2_020325_tagging_combined_4Unique_filled.csv'

# Load the CSV
df = pd.read_csv(csv_path)

# Optional: ensure correct data types (e.g., convert item_id to string if needed)
df['item_id'] = df['item_id'].astype(str)

# Define output Parquet path
parquet_path = csv_path.replace('.csv', '.parquet')

# Save as Parquet
df.to_parquet(parquet_path, index=False)

In [24]:
df.shape

(356, 13)